#Please note that a corresponding '.env' file should be next to this yml to define the Environment values used here.
#Since it contains passwords, it should not be shared in the source control.
#See README for instructions.

version: '3.4'
services:
    demohangfire.cli:
        image: ${DOCKER_REGISTRY-}demohangfirecli
        build:
            context: .
            dockerfile: DemoHangfire.CLI/Dockerfile
            network: 'host'
        environment:
            ConnectionString: "Data Source=demohangfire.mssql;Database=DemoHangfire;User=SA;Password=${SA_PASSWD};MultipleActiveResultSets=True"
        depends_on:
            - demohangfire.mssql
            - demohangfire.server1

    demohangfire.server1:
        image: ${DOCKER_REGISTRY-}demohangfireserver1
        build:
            context: .
            dockerfile: DemoHangfire.Server/Dockerfile
            network: 'host'
        environment:
            ConnectionString: "Data Source=demohangfire.mssql;Database=DemoHangfire;User=SA;Password=${SA_PASSWD};MultipleActiveResultSets=True"
        depends_on:
            - demohangfire.mssql

    demohangfire.mssql:
        image: ${DOCKER_REGISTRY-}demohangfiremssql
        build:
            args:
                SA_PASSWD: ${SA_PASSWD}
            context: .
            dockerfile: DemoHangfire.MSSQL/Dockerfile
            network: 'host'
        ports:
            - "1434:1433"